#!/bin/bash

# This line tells the computer to start interpreting this file as a Bash script.

for ((i=1; i<=100; i++))
do
    # This part starts a loop that goes from 1 to 100.

    if (( i % 3 == 0 )) && (( i % 5 == 0 )); then
        # This line checks if the number is divisible by both 3 and 5.
        echo "FizzBuzz"
        # If the number is divisible by both 3 and 5, it prints "FizzBuzz".
    elif (( i % 3 == 0 )); then
        # This line checks if the number is divisible by 3.
        echo "Fizz"
        # If the number is only divisible by 3, it prints "Fizz".
    elif (( i % 5 == 0 )); then
        # This line checks if the number is divisible by 5.
        echo "Buzz"
        # If the number is only divisible by 5, it prints "Buzz".
    else
        # If the number is not divisible by 3 or 5, it prints the number itself.
        echo $i
    fi
done

