#!/usr/bin/env bash
# This line specifies the interpreter to be used to execute the script, which is bash.

# This script displays the username, user id, and home directory for each line of /etc/passwd.

input="/etc/passwd"  # Assigns the file path /etc/passwd to the variable input.

while IFS= read -r line  # Start of the while loop: reads each line of the file /etc/passwd.
do
    echo "$line" | cut -d':' --fields=1,3,6  # Uses the cut command to extract fields from each line.
                                              # -d':' specifies ':' as the delimiter.
                                              # --fields=1,3,6 specifies to extract the 1st, 3rd, and 6th fields.
done < "$input"  # Redirects the contents of the file /etc/passwd as input for the while loop.

